name: Zeedz Integration Tests

on: [push]

jobs:
  vm-job:
    name: Zeedz Integration Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Flow CLI
        run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)" -- v0.33.1-sc-m5

      - name: Update PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm i

      - name: Integration Test ZeedzINO
        run: npm test ino --coverage

      - name: Integration Test ZeedzDrops
        run: npm test drops --coverage

      - name: Integration Test ZeedzMarketplace
        run: npm test marketplace --coverage
