name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          wget https://storage.googleapis.com/flow-cli/install.sh
          sh ./install.sh -- v0.30.2
          npm install
          npm test
